### ISSUE TITLE
Move seldom looked at portions of Makefile elsewhere

### ISSUE THREAD

**Issue by gkotian** [mineiros-io/build-tools#43]
Hey guys, first of all, thanks for the idea of abstracting away often run commands into a Makefile. Thanks to this simple move, I've saved countless hours of searching through my command history to find the one command that did the trick. I have now adopted the Makefile-way-of-working in all my projects.

One thing I noticed after using this approach widely is that there are portions of the Makefile that almost never change, and I almost never look at them. Specifically, these are parts that define the colour related variables, and the `help` target.

In the beginning, I moved these portions to the bottom of the file, but they still occupied more space than I liked. So now I've moved them into a separate (and hidden) `.Makefile.help` file which I include from the main Makefile using:
```Makefile
include .Makefile.help
```

This issue is mainly intended to share this approach with you (so I'll close it immediately afterwards). You could consider breaking up your Makefile into multiple portions, and users can choose to include only the ones they need (for instance, I'm not using snyk.io or terraform yet, so I've stripped out those parts altogether). In case you've already tried this, and deliberately decided not to do this, feel free to ignore me :)

FWIW, this is what my `.Makefile.help` currently looks like (had to add a `.txt` extension to make GitHub happy):
[.Makefile.help.txt](https://github.com/mineiros-io/build-tools/files/4772637/default.Makefile.help.txt)
(I should move the colour related stuff to a different file, but I'm just lazy)

**Comment by soerenmartius** [comment]
Hi @gkotian,

Thanks for this suggestion. That makes sense and we will consider it during our next Update. We are constantly working on improving our workflows. Moving never changing parts into a file that we simply include makes sense to me. @mariux what do you think?

**Comment by mariux** [comment]
Hi together, tahnks for your input. Yes, splitting it makes sense in bigger projects where you have a Makefile per-directory called recursively or you have Makefiles in several directories that you call manually. In those cases, you could easily share code between the various Makefiles.

This project comes with a single very short Makefile so code-sharing will not bring a benefit at the moment.
